### ISSUE TITLE
very slow map view for large repositories

### ISSUE THREAD

**Issue by jeroenvollenbrock** [git-up/GitUp#415]
I noticed that the responsiveness of GitUp becomes terrible when i use it on a large repo, for instance when i want to prepare a set of patches to the linux kernel. (This often involves some splitting and swapping). I think this is due to the re-rendering of the entire tree upon each change, while i'm only interested in the very top of it. Would it perhaps be possible to limit this view to show only commits up to a specific point in the history in order to increase the speed into usable levels?

**Comment by swisspol** [comment]
Do you mean the Map View?

**Comment by jeroenvollenbrock** [comment]
Yes, i mean the map view, excuse me for the ambiguity.

**Comment by swisspol** [comment]
Did you try hiding as many branches as possible?

**Comment by jeroenvollenbrock** [comment]
Yes, I've disabled all view options, but it remains slow. Even toggling just the "virtual branch tips" option takes two minutes to re-render the view.

**Comment by jeroenvollenbrock** [comment]
I also had only two local branches checked out, so i don't think that was causing any problems either

**Comment by jeroenvollenbrock** [comment]
It's actually quite easy to reproduce the problem, disable all view options, check out just the master branch of https://github.com/torvalds/linux, and try to swap the two topmost commits

**Comment by lilyball** [comment]
I really hope the new tag means someone is going to look at this issue. This performance problem is why I've largely stopped using GitUp, even though the repo I'm working on isn't nearly as large as the Linux repo.

**Comment by lucasderraugh** [comment]
Unfortunately these performance issues are not something we’ve addressed. I understand the frustration though and perhaps I’ll try to focus on some of these perf issues for the next release.

**Comment by richardtop** [comment]
Hiding remote branches solved the issue for me. Performance is still not stellar, but way better than if showing all of the branches.

**Comment by jfirebaugh** [comment]
I did some profiling and at least for me, the performance problems seem less to do with the size of the repository and more with reading and writing large snapshot files -- `<repo>/.git/co.gitup.mac/snapshots.data`. When I moved that file aside and restarted GitUp, most operations were fast again.

**Comment by richardtop** [comment]
I can confirm, this is a huge issue even when the remote branches are hidden.

The issue is reproducible when switching between the "map" view and the "commit editor" view (cmd+1 / cmd+2) or between the "commit editor" and the "stashed changes" view.

It appears there is some sort of a delay when switching between the commit editor and some other view.

**Comment by snowblink** [comment]
> I did some profiling and at least for me, the performance problems seem less to do with the size of the repository and more with reading and writing large snapshot files -- `<repo>/.git/co.gitup.mac/snapshots.data`. When I moved that file aside and restarted GitUp, most operations were fast again.

Is there some sort of option to not use snapshots? Or limit how far back they go? I don't think I've every used the functionality and would probably drop to `git reflog` if I really needed to anything.

**Comment by richardtop** [comment]
Removing those files doesn't really solve the problem, the performance is still not at the acceptable level even on high-end machines.

**Comment by AlexMoutonNoble** [comment]
Moving snapshots not seeming to help here

**Comment by jfirebaugh** [comment]
The root cause in my case was thousands of remote-tracking branches. I did the following to limit what remote branches get tracked by default, and remove most of the existing ones:

```
git remote set-branches origin master # Fetch only `master` as a remote-tracking branch
git branch -r | xargs -L 1 git branch -rD # Delete all existing remote-tracking branches
git fetch
```

To selectively add additional remote-tracking branches, do this:

```
git remote set-branches --add origin <branch>
git fetch
```

If you don't care about tags, you can also filter those out:

```
git config remote.origin.tagOpt --no-tags # Don't fetch tags
git tag | xargs -L 1 git tag -d # Delete existing local tag refs
```

After doing this gitup is snappy again! 🎉

**Comment by HotFusionMan** [comment]
Running the following Git commands (learned from https://www.git-tower.com/blog/git-performance/ ) in my slow-map-view-rendering repo has made the slowness almost unnoticeable immediately afterward. There is a beachball for about a second after switching from another app to GitUp (the occasion when I always notice the slowness), starting about half a second after switching to GitUp
```sh
git config core.fsmonitor true
git config core.untrackedcache true
```
I had also tried
```sh
git config feature.manyFiles true
git update-index --index-version 4
```
but discovered that GitUp does not handle reading that version of index well, so I reverted those settings (I didn't know what index version I had started at, but 3 seems to work OK).
