### ISSUE TITLE
Glitch when dismissing a commit tooltip view in the dark mode

### ISSUE THREAD

**Issue by richardtop** [git-up/GitUp#654]
<img width="476" alt="Skärmavbild 2020-02-18 kl  21 40 41" src="https://user-images.githubusercontent.com/8013017/74771790-75e98900-5297-11ea-975e-f921d200e1de.png">

Steps to reproduce:
1. Select a commit to open a "commit tooltip view"
2. Press "spacebar" to show "commit detail view" and then press "spacebar" again to dismiss it.
3. Click somewhere else on the canvas to dismiss the tooltip
4. Observe the issue as on the screenshots

**Comment by lucasderraugh** [comment]
This doesn't happen every time for you does it? I'm always in Dark mode and haven't seen this.

**Comment by richardtop** [comment]
Updated the steps, so that it could be reproducible consistently.

**Comment by lucasderraugh** [comment]
@richardtop Steps 2 and 3 seem impossible to me. If you click elsewhere to dismiss the tooltip, the selection goes away, so hitting spacebar doesn't do anything.

**Comment by richardtop** [comment]
My bad, I've made a mistake in the sequence. Fixed now.
The "spacebar" step  should be just after opening a tooltip view.

**Comment by lucasderraugh** [comment]
Hmm, still doesn’t reproduce for me. I’ll keep on the lookout for it. What OS version are you running?

**Comment by richardtop** [comment]
10.15.2 (19C57)

**Comment by lucasderraugh** [comment]
I'm running 10.15.3, not that I expect that to change anything. I'll keep my eye out for it though.

**Comment by richardtop** [comment]
I also tried on 10.15.3 and cannot consistently reproduce the issue.

**Comment by lucasderraugh** [comment]
This should now be fixed in ToT. This will land in the next release. Probably in the continuous channel next week (stable the week after if all goes well).

**Comment by lucasderraugh** [comment]
This should have been addressed in our 1.2 release which is now available on the continuous channel.
