### ISSUE TITLE
Stash sometimes will not recognise changes in the repo

### ISSUE THREAD

**Issue by daghoidahl** [git-up/GitUp#88]
When only <del>one line in</del> one file has changed, stashing often fails with this message:

> Cannot stash changes - There is nothing to stash.

**Comment by daghoidahl** [comment]
This just happened again, with several lines changed in one file. I don't know exactly when this bug is triggered.

**Comment by swisspol** [comment]
I've observed this myself a couple times: seems like an extremely rare race condition. Restating GitUp should fix it.

**Comment by deyton** [comment]
When this happens to me, switching to commit view and staging the changes seems to make the stash work.

**Comment by daghoidahl** [comment]
@deyton That has worked for me, too. 

@swisspol This bug occurs quite often for me. I often switch to other git clients as well, maybe that makes a difference.

**Comment by swisspol** [comment]
You might wanna try on the latest pre-release build: b1016. It has a new libgit2 and maybe it fixes this bug...

**Comment by daghoidahl** [comment]
@swisspol I have upgraded. I'll let you know within a week if I still have problems.

**Comment by daghoidahl** [comment]
@swisspol Looks like the bug has been fixed. I haven't noticed it since upgrading to b1016.

**Comment by swisspol** [comment]
Thanks for the update

**Comment by andrewmichaelson** [comment]
I've seen this bug appear using GitUp 1.0.11 (1027) with 1 line changed in 1 file. Restarting GitUp didn't fix it. Staging the file before stashing fixed it.
